name: Cache CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Cache dependencies (Python pip example)
      - name: Cache dependencies
        id: cache-deps   # ✅ must have an ID to reference outputs
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-f2815ea

      # Step 3: Prime the cache
      - name: prime-cache-f2815ea
        run: |
          echo "Cache hit? ${{ steps.cache-deps.outputs.cache-hit }}"
          if [ "${{ steps.cache-deps.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi
